title: How I Automated This !
subtitle: Une série d'article sur l'automatisation de tâches et aussi plein d'autre truc
description: >- # this means to ignore newlines until "baseurl:"
  Une série d'article sur l'automatisation de tâches et aussi plein d'autre truc.

url: "https://laurentlienhard.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
#    - text: Gallery
#      url: /gallery
#    - text: Shop
#      url : /shop
#    - text: Contact
#      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: LIENHARD Laurent
author_bio: Auto-Didacte en PowerShell, Co-fondateur et animateur du French PowerShell & DevOps UserGroup
author_email: "laurent@lienhard.fr"
author_location: Alsace, France
#author_website_url: "https://sujaykundu.com"
typewrite-text: Une série d'article sur l'automatisation de tâches et aussi plein d'autre truc
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Ophèa
              company_logo: Ophea.png
              company_url: https://www.ophea.fr/
              designation: Administrateur Systèmes et Office 365
#              description: Worked on various Google Products
              visibility: true
            - company_name: OCI
              company_logo: OCI.png
              company_url: https://www.oci.fr/
              designation: Développeur
#              description: Worked on various Azure Cloud Products
              visibility: true

# Education
author_education_details:
              - college_logo: afpa.png
                college_name: AFPA
                college_url: https://www.afpa.fr/centre/centre-de-mulhouse
                college_degree: Equivalence Bac+2
                description: Analyste-Programmeur en informatique industrielle
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# social links
twitter_username: IronTUX
github_username:  LaurentLienhard
facebook_username: laurent.lienhard.5
linkedin_username: laurent-lienhard-61680528
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: IronTUX

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
